version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "dbdata:/var/lib/postgresql/data/pgdata"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  phoenix:
    image: marcelocg/phoenix
    restart: always
    working_dir: /phoenix
    command: mix phx.server
    volumes:
      - "./:/phoenix"
    ports:
      - 8000:4000

volumes:
  dbdata:
